"""updated order model

Revision ID: 303561ab2666
Revises: 8778860281cc
Create Date: 2025-05-03 23:56:16.735519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303561ab2666'
down_revision: Union[str, None] = '8778860281cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None, recreate="always") as batch_op:
        # Удаление старых колонок
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')

        # Изменение колонок
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              existing_nullable=True)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

        # Добавление нового foreign key внутри batch-контекста
        batch_op.create_foreign_key(
            "fk_order_user_id",
            "users",
            ["user_id"],
            ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None, recreate="always") as batch_op:
        # Восстановление колонок
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))

        # Удаление нового foreign key
        batch_op.drop_constraint("fk_order_user_id", type_="foreignkey")

        # Восстановление старого foreign key
        batch_op.create_foreign_key(
            "fk_order_product",
            "products",
            ["product_id"],
            ["id"]
        )

        # Возврат оригинальных параметров колонок
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              server_default=None,
                              existing_nullable=True)
    # ### end Alembic commands ###
